const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SOURCE_APP = path.join(ROOT, 'src', 'app.js');
const SOURCE_CONSTANTS = path.join(ROOT, 'src', 'constants.js');
const SOURCE_FORMATTERS = path.join(ROOT, 'src', 'formatters.js');
const SOURCE_COMPONENTS = path.join(ROOT, 'src', 'components.js');
const SOURCE_GAME_COMPONENTS = path.join(ROOT, 'src', 'game-components.js');
const SOURCE_GAME_STATE = path.join(ROOT, 'src', 'game-state.js');
const SOURCE_DIALOGS = path.join(ROOT, 'src', 'dialogs.js');
const SOURCE_SETUP_SCREEN = path.join(ROOT, 'src', 'setup-screen.js');
const SOURCE_RULES = path.join(ROOT, 'src', 'rules.js');
const SOURCE_STORAGE = path.join(ROOT, 'src', 'storage.js');
const BUILT_APP = path.join(ROOT, 'app.js');
const BUILT_CONSTANTS = path.join(ROOT, 'constants.js');
const BUILT_FORMATTERS = path.join(ROOT, 'formatters.js');
const BUILT_COMPONENTS = path.join(ROOT, 'components.js');
const BUILT_GAME_COMPONENTS = path.join(ROOT, 'game-components.js');
const BUILT_GAME_STATE = path.join(ROOT, 'game-state.js');
const BUILT_DIALOGS = path.join(ROOT, 'dialogs.js');
const BUILT_SETUP_SCREEN = path.join(ROOT, 'setup-screen.js');
const BUILT_RULES = path.join(ROOT, 'rules.js');
const BUILT_STORAGE = path.join(ROOT, 'storage.js');
const INDEX_HTML = path.join(ROOT, 'index.html');
const SERVICE_WORKER = path.join(ROOT, 'sw.js');

function read(file) {
  return fs.readFileSync(file, 'utf8');
}

function write(file, content) {
  fs.writeFileSync(file, content, 'utf8');
}

function currentVersion() {
  const index = read(INDEX_HTML);
  const match = index.match(/V\d{8}_\d{4}/);
  if (!match) throw new Error('Unable to find current app version in index.html');
  return match[0];
}

function nextVersion() {
  const explicit = process.argv[2];
  if (explicit) {
    if (!/^V\d{8}_\d{4}$/.test(explicit)) {
      throw new Error('Version must look like V20260617_0115');
    }
    return explicit;
  }

  const now = new Date();
  const pad = value => String(value).padStart(2, '0');
  return [
    'V',
    now.getFullYear(),
    pad(now.getMonth() + 1),
    pad(now.getDate()),
    '_',
    pad(now.getHours()),
    pad(now.getMinutes()),
  ].join('');
}

function replaceVersions(content, version) {
  return content.replace(/V\d{8}_\d{4}/g, version);
}

function normalizeAppSource(content) {
  return content
    .replace(/^\uFEFF/, '')
    .replace(/^\/\/ Source of truth for the Molkky React app\.\r?\n\/\/ Edit this file, then run: node scripts\/build\.js \[VERSION\]\r?\n\r?\n/, '')
    .replace(/^\/\/ Generated by scripts\/build\.js from src\/app\.js\.\r?\n\/\/ Edit src\/app\.js, then run: node scripts\/build\.js \[VERSION\]\r?\n\r?\n/, '')
    .replace(/^\/\/ Generated from index\.html <script type="text\/babel">\.\r?\n\/\/ Do not edit this file directly unless you also remove the source JSX workflow\.\r?\n\r?\n/, '');
}

function buildApp(version) {
  const source = replaceVersions(normalizeAppSource(read(SOURCE_APP)).trimEnd(), version);
  const banner = [
    '// Generated by scripts/build.js from src/app.js.',
    '// Edit src/app.js, then run: node scripts/build.js [VERSION]',
    '',
  ].join('\n');

  write(BUILT_APP, `${banner}${source}\n`);
}

function buildRules() {
  write(BUILT_RULES, read(SOURCE_RULES).trimEnd() + '\n');
}

function buildConstants() {
  write(BUILT_CONSTANTS, read(SOURCE_CONSTANTS).trimEnd() + '\n');
}

function buildFormatters() {
  write(BUILT_FORMATTERS, read(SOURCE_FORMATTERS).trimEnd() + '\n');
}

function buildComponents() {
  write(BUILT_COMPONENTS, read(SOURCE_COMPONENTS).trimEnd() + '\n');
}

function buildGameComponents() {
  write(BUILT_GAME_COMPONENTS, read(SOURCE_GAME_COMPONENTS).trimEnd() + '\n');
}

function buildGameState() {
  write(BUILT_GAME_STATE, read(SOURCE_GAME_STATE).trimEnd() + '\n');
}

function buildDialogs() {
  write(BUILT_DIALOGS, read(SOURCE_DIALOGS).trimEnd() + '\n');
}

function buildSetupScreen() {
  write(BUILT_SETUP_SCREEN, read(SOURCE_SETUP_SCREEN).trimEnd() + '\n');
}

function buildStorage() {
  write(BUILT_STORAGE, read(SOURCE_STORAGE).trimEnd() + '\n');
}

function syncVersion(file, version) {
  write(file, replaceVersions(read(file), version));
}

const version = process.argv[2] ? nextVersion() : currentVersion();

buildApp(version);
buildConstants();
buildFormatters();
buildComponents();
buildGameComponents();
buildGameState();
buildDialogs();
buildSetupScreen();
buildRules();
buildStorage();
syncVersion(INDEX_HTML, version);
syncVersion(SERVICE_WORKER, version);
syncVersion(SOURCE_APP, version);

console.log(`Built app.js from src/app.js (${version})`);
